<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-HQBDKGDN" failures="3" tests="14" name="End to End testing" time="127.855" errors="0" timestamp="2021-11-12T13:46:26 IST">
  <testcase classname="com.crm.qa.tests.LoginPageTest" name="loginPageTitleTest" time="0.038"/>
  <testcase classname="com.crm.qa.tests.HomePageTest" name="verifyHomePageTitle" time="0.011"/>
  <testcase classname="com.crm.qa.tests.LoginPageTest" name="loginPageLogoTest" time="0.106"/>
  <testcase classname="com.crm.qa.tests.ContactsPageTest" name="verifySelectContactsByName" time="0.163"/>
  <testcase classname="com.crm.qa.tests.HomePageTest" name="clickOnContactsLink" time="2.204">
    <skipped/>
  </testcase> <!-- clickOnContactsLink -->
  <testcase classname="com.crm.qa.tests.LoginPageTest" name="loginPageLoginTest" time="6.277"/>
  <testcase classname="com.crm.qa.tests.ContactsPageTest" name="verifyCreateNewContact" time="2.672">
    <skipped/>
  </testcase> <!-- verifyCreateNewContact -->
  <testcase classname="com.crm.qa.tests.HomePageTest" name="clickOnContactsLink" time="1.459">
    <skipped/>
  </testcase> <!-- clickOnContactsLink -->
  <testcase classname="com.crm.qa.tests.ContactsPageTest" name="verifyCreateNewContact" time="2.332">
    <skipped/>
  </testcase> <!-- verifyCreateNewContact -->
  <testcase classname="com.crm.qa.tests.HomePageTest" name="clickOnContactsLink" time="1.726">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.crm.qa.tests.HomePageTest.clickOnContactsLink(HomePageTest.java:58)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
]]>
    </failure>
  </testcase> <!-- clickOnContactsLink -->
  <testcase classname="com.crm.qa.tests.ContactsPageTest" name="verifyCreateNewContact" time="2.04">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.crm.qa.tests.ContactsPageTest.verifyCreateNewContact(ContactsPageTest.java:59)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
]]>
    </failure>
  </testcase> <!-- verifyCreateNewContact -->
  <testcase classname="com.crm.qa.tests.ContactsPageTest" name="verifyCreateNewContact" time="2.242">
    <skipped/>
  </testcase> <!-- verifyCreateNewContact -->
  <testcase classname="com.crm.qa.tests.ContactsPageTest" name="verifyCreateNewContact" time="1.868">
    <skipped/>
  </testcase> <!-- verifyCreateNewContact -->
  <testcase classname="com.crm.qa.tests.ContactsPageTest" name="verifyCreateNewContact" time="2.237">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.crm.qa.tests.ContactsPageTest.verifyCreateNewContact(ContactsPageTest.java:59)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
]]>
    </failure>
  </testcase> <!-- verifyCreateNewContact -->
</testsuite> <!-- End to End testing -->
